Apple m1 opt homebrew support (Fixes #153) (#154)
* Add rspec tests for Apple M1 silicon Homebrew path helper

* Add Homebrew.install_path() helper for Apple M1 silicon (arm64)

* Add HomebrewWrapper class to use install_path() M1 detection function

* Convert /usr/local to use install_path() for M1 /opt/homebrew support

* Fixing InSpec tests for macOS M1 / arm64 and x86_64

Note: InSpec running as root will not have PATH to Homebrew set up.  Thus, package checks will fail if `inspec --sudo` is used

* Remove deprecated full option for Homebrew (Breaking upstream change!)

Error was:

    Error: Calling the `--full` switch is disabled! There is no replacement.

* Use private macOS Vagrant boxes w/up-to-date Chef Infra & InSpec for testing this cookbook

* Add Homebrew.repository_path() helper for Apple M1 silicon (arm64)

* Use HomebrewWrapper.repository_path() for homebrew_tap resource idempotency on Apple M1 silicon (arm64)

* Revert "Use private macOS Vagrant boxes [...]" for upstream pull request

This reverts commit 5a9f4629e78d7eba8c382c203d2fced12a1193f2.

* CHANGELOG.md: Update Unreleased section w/Apple M1 changes

* CHANGELOG.md: Fix markdownlint issues

* Autocorrect Cookstyle issues